# Globs for files and directories that Gemini should ignore.
# This helps focus the AI on relevant code and avoids processing
# large, irrelevant, or sensitive files.
ignore:
  - .git/**
  - node_modules/**
  - dist/**
  - build/**
  - .DS_Store
  - "*.log"
  - "package-lock.json"
  - "yarn.lock"
