// ABOUT: TypeScript type definitions for the Cloudflare Worker
// ABOUT: Defines interfaces for environment bindings and data structures

/**
 * Cloudflare Worker environment bindings
 * Contains secrets, KV namespaces, and other runtime configuration
 */
export interface Env {
  // Authentication secrets
  ADMIN_EMAIL: string;
  JWT_SECRET: string;
  RESEND_API_KEY: string;
  GITHUB_TOKEN: string;

  // KV namespaces
  AUTH_KV: KVNamespace; // Stores magic link tokens
  RATE_LIMIT_KV: KVNamespace; // Stores rate limit data
}

/**
 * Status of an update
 * - draft: Not visible to public, work in progress
 * - published: Live on site, visible to all
 * - unpublished: Previously published but now hidden (soft delete)
 */
export type UpdateStatus = 'draft' | 'published' | 'unpublished';

/**
 * Individual update stored as {slug}.json
 * Contains all metadata and content for a single blog update
 */
export interface Update {
  slug: string;
  title: string;
  excerpt: string; // Empty string if not provided, generated at display time
  content: string; // Markdown content
  status: UpdateStatus;
  publishedDate: string; // ISO 8601 format
  editedDate: string; // ISO 8601 format
  author: string;
  images: string[]; // Array of image paths relative to site root
}

/**
 * Entry in the index.json file
 * Lightweight summary for listing pages and RSS feed
 */
export interface UpdateIndexEntry {
  slug: string;
  title: string;
  excerpt: string; // Custom excerpt or first 150 chars of content
  publishedDate: string; // ISO 8601 format
  status: UpdateStatus;
}

/**
 * Index file structure (index.json)
 * Generated by GitHub Action, contains only published updates
 */
export interface UpdateIndex {
  updates: UpdateIndexEntry[];
}
