// ABOUT: TypeScript type definitions for the Cloudflare Worker
// ABOUT: Defines interfaces for environment bindings and data structures

/**
 * Cloudflare Worker environment bindings
 * Contains secrets, KV namespaces, and other runtime configuration
 * All properties are optional to support incremental implementation across phases
 */
export interface Env {
  // Authentication secrets (Phase 3+)
  ADMIN_EMAIL?: string;
  JWT_SECRET?: string;
  RESEND_API_KEY?: string;

  // GitHub integration (Phase 4+)
  GITHUB_TOKEN?: string;

  // KV namespaces (Phase 3+)
  AUTH_KV?: KVNamespace; // Stores magic link tokens
  RATE_LIMIT_KV?: KVNamespace; // Stores rate limit data

  // Static assets binding — use env.ASSETS.fetch() to serve files from public/
  ASSETS?: Fetcher;

  // Google Search Console service-account JSON (stringified)
  GSC_SERVICE_ACCOUNT_JSON?: string;

  // KV namespace storing GSC snapshots and alert dedup keys
  GSC_KV?: KVNamespace;

  // Cloudflare Email Sending binding (beta) — used by the notifier with Resend fallback.
  // Sending magic-link auth emails continues to use Resend directly.
  SEND_EMAIL?: SendEmail;
}

/**
 * Status of an update
 * - draft: Not visible to public, work in progress
 * - published: Live on site, visible to all
 * - unpublished: Previously published but now hidden (soft delete)
 */
export type UpdateStatus = 'draft' | 'published' | 'unpublished';

/**
 * Individual update stored as {slug}.json
 * Contains all metadata and content for a single blog update
 */
export interface Update {
  slug: string;
  title: string;
  excerpt: string; // Empty string if not provided, generated at display time
  content: string; // Markdown content
  status: UpdateStatus;
  publishedDate: string; // ISO 8601 format
  editedDate: string; // ISO 8601 format
  author: string;
  images: string[]; // Array of image paths relative to site root
}

/**
 * Entry in the index.json file
 * Lightweight summary for listing pages and RSS feed
 */
export interface UpdateIndexEntry {
  slug: string;
  title: string;
  excerpt: string; // Custom excerpt or first 150 chars of content
  publishedDate: string; // ISO 8601 format
  status: UpdateStatus;
}

/**
 * Index file structure (index.json)
 * Generated by GitHub Action, contains only published updates
 */
export interface UpdateIndex {
  updates: UpdateIndexEntry[];
}

/**
 * /now page content stored in content.json
 * Contains markdown content and last update timestamp
 */
export interface NowContent {
  markdown: string;
  lastUpdated: string; // ISO 8601 format
}

/**
 * /now page snapshot stored in snapshots/YYYYMMDD.json
 * Historical version of /now content at a specific date
 */
export interface NowSnapshot {
  markdown: string;
  snapshotDate: string; // ISO 8601 format
}

/**
 * Entry in the snapshots index file
 * Lightweight summary for listing snapshots in admin UI
 */
export interface NowSnapshotIndexEntry {
  date: string; // YYYYMMDD format (e.g., "20260330")
  snapshotDate: string; // ISO 8601 format
  preview: string; // First 150 chars of content
}

/**
 * Snapshots index file structure (snapshots/index.json)
 * Contains metadata for all snapshots
 */
export interface NowSnapshotsIndex {
  snapshots: NowSnapshotIndexEntry[];
}

/**
 * Types of alerts the scheduled GSC poll can raise.
 * Keep in sync with SPECIFICATIONS/gsc-insights-and-alerts.md.
 */
export type GSCAlertType =
  | 'indexed-drop'
  | 'sitemap-error'
  | 'new-crawl-error'
  | 'impressions-drop';

export interface GSCAlert {
  type: GSCAlertType;
  severity: 'high' | 'medium';
  message: string;
  detectedAt: string;
  emailSent: boolean;
}

export interface GSCPendingAlert {
  type: GSCAlertType;
  firstDetectedAt: string;
}

export interface GSCSitemapStatus {
  path: string;
  lastSubmitted: string | null;
  lastDownloaded: string | null;
  errors: number;
  warnings: number;
  submitted: number;
  indexed: number;
}

export interface GSCTopQuery {
  query: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface GSCPerformance {
  period: '28d';
  totalClicks: number;
  totalImpressions: number;
  avgCtr: number;
  avgPosition: number;
  topQueries: GSCTopQuery[];
  priorPeriodClicks: number;
  priorPeriodImpressions: number;
}

export interface GSCEmailDelivery {
  lastProvider: 'cf' | 'resend' | 'none' | null;
  lastSuccessAt: string | null;
  lastErrorAt: string | null;
}

export interface GSCSnapshot {
  capturedAt: string;
  siteUrl: string;
  sitemaps: GSCSitemapStatus[];
  indexing: {
    indexedCount: number;
  };
  performance: GSCPerformance;
  alerts: GSCAlert[];
  pendingAlerts: GSCPendingAlert[];
  emailDelivery: GSCEmailDelivery;
}
