// ABOUT: TypeScript type definitions for the Cloudflare Worker
// ABOUT: Defines interfaces for environment bindings and data structures

/**
 * Cloudflare Worker environment bindings
 * Contains secrets, KV namespaces, and other runtime configuration
 * All properties are optional to support incremental implementation across phases
 */
export interface Env {
  // Authentication secrets (Phase 3+)
  ADMIN_EMAIL?: string;
  JWT_SECRET?: string;
  RESEND_API_KEY?: string;

  // GitHub integration (Phase 4+)
  GITHUB_TOKEN?: string;

  // KV namespaces (Phase 3+)
  AUTH_KV?: KVNamespace; // Stores magic link tokens
  RATE_LIMIT_KV?: KVNamespace; // Stores rate limit data

  // Static assets binding — use env.ASSETS.fetch() to serve files from public/
  ASSETS?: Fetcher;

  // Google Search Console service-account JSON (stringified)
  GSC_SERVICE_ACCOUNT_JSON?: string;

  // KV namespace storing GSC snapshots and alert dedup keys
  GSC_KV?: KVNamespace;

  // Cloudflare Email Sending binding (beta) — used by the notifier with Resend fallback.
  // Sending magic-link auth emails continues to use Resend directly.
  SEND_EMAIL?: SendEmail;
}

/**
 * Status of an update
 * - draft: Not visible to public, work in progress
 * - published: Live on site, visible to all
 * - unpublished: Previously published but now hidden (soft delete)
 */
export type UpdateStatus = 'draft' | 'published' | 'unpublished';

/**
 * Individual update stored as {slug}.json
 * Contains all metadata and content for a single blog update
 */
export interface Update {
  slug: string;
  title: string;
  excerpt: string; // Empty string if not provided, generated at display time
  content: string; // Markdown content
  status: UpdateStatus;
  publishedDate: string; // ISO 8601 format
  editedDate: string; // ISO 8601 format
  author: string;
  images: string[]; // Array of image paths relative to site root
}

/**
 * Entry in the index.json file
 * Lightweight summary for listing pages and RSS feed
 */
export interface UpdateIndexEntry {
  slug: string;
  title: string;
  excerpt: string; // Custom excerpt or first 150 chars of content
  publishedDate: string; // ISO 8601 format
  status: UpdateStatus;
}

/**
 * Index file structure (index.json)
 * Generated by GitHub Action, contains only published updates
 */
export interface UpdateIndex {
  updates: UpdateIndexEntry[];
}

/**
 * /now page content stored in content.json
 * Contains markdown content and last update timestamp
 */
export interface NowContent {
  markdown: string;
  lastUpdated: string; // ISO 8601 format
}

/**
 * /now page snapshot stored in snapshots/YYYYMMDD.json
 * Historical version of /now content at a specific date
 */
export interface NowSnapshot {
  markdown: string;
  snapshotDate: string; // ISO 8601 format
}

/**
 * Entry in the snapshots index file
 * Lightweight summary for listing snapshots in admin UI
 */
export interface NowSnapshotIndexEntry {
  date: string; // YYYYMMDD format (e.g., "20260330")
  snapshotDate: string; // ISO 8601 format
  preview: string; // First 150 chars of content
}

/**
 * Snapshots index file structure (snapshots/index.json)
 * Contains metadata for all snapshots
 */
export interface NowSnapshotsIndex {
  snapshots: NowSnapshotIndexEntry[];
}

/**
 * Types of alerts the scheduled GSC poll can raise.
 * Keep in sync with SPECIFICATIONS/gsc-insights-and-alerts.md.
 */
export type GSCAlertType =
  | 'indexed-drop'
  | 'sitemap-error'
  | 'new-crawl-warning'
  | 'impressions-drop';

export interface GSCAlert {
  type: GSCAlertType;
  severity: 'high' | 'medium';
  subject: string; // short, magnitude-aware summary used for email subject lines
  message: string; // full message body explaining the condition
  firstDetectedAt: string; // ISO 8601 — when the condition was *first* observed
                           // (preserved from the original pending entry through
                           // graduation + continuation, so the UI can render
                           // "seen for N days")
  detectedAt: string;      // ISO 8601 — when this run observed the condition
  emailSent: boolean;
  discriminator?: string;  // optional per-alert dedup key (e.g. sitemap path)
}

export interface GSCPendingAlert {
  type: GSCAlertType;
  firstDetectedAt: string;
}

export interface GSCSitemapStatus {
  path: string;
  lastSubmitted: string | null;
  lastDownloaded: string | null;
  errors: number;
  warnings: number;
  submitted: number;
  indexed: number;
}

export interface GSCTopQuery {
  query: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface GSCPerformance {
  period: '28d';
  totalClicks: number;
  totalImpressions: number;
  avgCtr: number;
  avgPosition: number;
  topQueries: GSCTopQuery[];
  priorPeriodClicks: number;
  priorPeriodImpressions: number;
}

/**
 * Email delivery state surfaced on the dashboard widget.
 *
 * `lastProvider` semantics:
 *   `null`     — no delivery has been attempted yet (fresh state, no alerts fired)
 *   `'cf'`     — most recent attempt succeeded via Cloudflare Email Sending
 *   `'resend'` — most recent attempt succeeded via Resend (CF failed, fallback worked)
 *   `'none'`   — most recent attempt failed at both providers
 *
 * Resolves GitHub issue #32: explicit documentation of the semantics
 * the dashboard widget relies on.
 */
export interface GSCEmailDelivery {
  lastProvider: 'cf' | 'resend' | 'none' | null;
  lastSuccessAt: string | null;
  lastErrorAt: string | null;
}

export interface GSCSnapshot {
  capturedAt: string;
  siteUrl: string;
  sitemaps: GSCSitemapStatus[];
  indexing: {
    indexedCount: number;
    /**
     * Indexed count from the 28-day-ago history snapshot, or `null` if no
     * history snapshot exists for that date. Drives the "+2 vs 28d ago"
     * delta on the Indexed tile.
     * Optional for back-compat with snapshots written before this field
     * existed; treat `undefined` as `null`.
     */
    priorPeriodIndexedCount?: number | null;
  };
  performance: GSCPerformance;
  alerts: GSCAlert[];
  pendingAlerts: GSCPendingAlert[];
  emailDelivery: GSCEmailDelivery;
  /**
   * Which entry path produced this snapshot. `cron` runs dispatch alert
   * emails; `manual` (admin refresh button) skips dispatch and relies on
   * the next cron to deliver. The widget surfaces a caveat when a manual
   * refresh graduates an alert so the admin understands the email lag.
   *
   * Optional for back-compat with snapshots written before this field
   * existed; treat `undefined` as `'cron'` (the historic behaviour).
   */
  source?: 'cron' | 'manual';
}
